-- =============================================================
-- 06_views.sql
-- Aggregation views built on top of CLEAN.FLIGHT_CLEAN
-- All views are filtered to flights involving DFW (origin or dest)
--
-- Views:
--   V_ONTIME_BY_AIRLINE  -- on-time performance metrics per carrier
--   V_DELAY_CAUSES       -- delay minute breakdown by cause per carrier
--   V_MONTHLY_TRENDS     -- volume and performance trends by month
--
-- Views reflect current validated data automatically as new
-- months are loaded and SP_VALIDATE_FLIGHTS is rerun.
-- =============================================================

USE DATABASE DFW_FLIGHTS;
USE SCHEMA CLEAN;

-- View 1: On-time performance by airline at DFW
CREATE OR REPLACE VIEW V_ONTIME_BY_AIRLINE AS
SELECT
    REPORTING_AIRLINE,
    COUNT(*) AS TOTAL_FLIGHTS,
    SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END) AS CANCELLED_FLIGHTS,
    COUNT(*) - SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END) AS OPERATED_FLIGHTS,
    SUM(CASE WHEN DEP_DEL15 = 1 THEN 1 ELSE 0 END) AS DEP_DELAYED_FLIGHTS,
    SUM(CASE WHEN ARR_DEL15 = 1 AND CANCELLED = 0 THEN 1 ELSE 0 END) AS ARR_DELAYED_FLIGHTS,
    ROUND(100.0 * SUM(CASE WHEN DEP_DEL15 = 0 AND CANCELLED = 0 THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*) - SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END), 0), 2)
        AS DEP_ONTIME_PCT,
    ROUND(100.0 * SUM(CASE WHEN ARR_DEL15 = 0 AND CANCELLED = 0 THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*) - SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END), 0), 2)
        AS ARR_ONTIME_PCT,
    ROUND(AVG(CASE WHEN CANCELLED = 0 THEN DEP_DELAY END), 2) AS AVG_DEP_DELAY_MINS,
    ROUND(AVG(CASE WHEN CANCELLED = 0 THEN ARR_DELAY END), 2) AS AVG_ARR_DELAY_MINS,
    ROUND(100.0 * SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END)
        / COUNT(*), 2) AS CANCELLATION_RATE_PCT
FROM DFW_FLIGHTS.CLEAN.FLIGHT_CLEAN
WHERE ORIGIN = 'DFW' OR DEST = 'DFW'
GROUP BY REPORTING_AIRLINE
ORDER BY ARR_ONTIME_PCT DESC;

-- View 2: Delay cause breakdown by airline at DFW
-- Restricted to operated, delayed flights with at least one
-- delay cause attributed
CREATE OR REPLACE VIEW V_DELAY_CAUSES AS
SELECT
    REPORTING_AIRLINE,
    COUNT(*) AS DELAYED_FLIGHTS,
    ROUND(SUM(CARRIER_DELAY), 0) AS TOTAL_CARRIER_DELAY_MINS,
    ROUND(SUM(WEATHER_DELAY), 0) AS TOTAL_WEATHER_DELAY_MINS,
    ROUND(SUM(NAS_DELAY), 0) AS TOTAL_NAS_DELAY_MINS,
    ROUND(SUM(SECURITY_DELAY), 0) AS TOTAL_SECURITY_DELAY_MINS,
    ROUND(SUM(LATE_AIRCRAFT_DELAY), 0) AS TOTAL_LATE_AIRCRAFT_DELAY_MINS,
    ROUND(SUM(CARRIER_DELAY) + SUM(WEATHER_DELAY) + SUM(NAS_DELAY)
        + SUM(SECURITY_DELAY) + SUM(LATE_AIRCRAFT_DELAY), 0) AS TOTAL_DELAY_MINS,
    ROUND(100.0 * SUM(CARRIER_DELAY)
        / NULLIF(SUM(CARRIER_DELAY) + SUM(WEATHER_DELAY) + SUM(NAS_DELAY)
        + SUM(SECURITY_DELAY) + SUM(LATE_AIRCRAFT_DELAY), 0), 2) AS CARRIER_DELAY_PCT,
    ROUND(100.0 * SUM(WEATHER_DELAY)
        / NULLIF(SUM(CARRIER_DELAY) + SUM(WEATHER_DELAY) + SUM(NAS_DELAY)
        + SUM(SECURITY_DELAY) + SUM(LATE_AIRCRAFT_DELAY), 0), 2) AS WEATHER_DELAY_PCT,
    ROUND(100.0 * SUM(NAS_DELAY)
        / NULLIF(SUM(CARRIER_DELAY) + SUM(WEATHER_DELAY) + SUM(NAS_DELAY)
        + SUM(SECURITY_DELAY) + SUM(LATE_AIRCRAFT_DELAY), 0), 2) AS NAS_DELAY_PCT,
    ROUND(100.0 * SUM(SECURITY_DELAY)
        / NULLIF(SUM(CARRIER_DELAY) + SUM(WEATHER_DELAY) + SUM(NAS_DELAY)
        + SUM(SECURITY_DELAY) + SUM(LATE_AIRCRAFT_DELAY), 0), 2) AS SECURITY_DELAY_PCT,
    ROUND(100.0 * SUM(LATE_AIRCRAFT_DELAY)
        / NULLIF(SUM(CARRIER_DELAY) + SUM(WEATHER_DELAY) + SUM(NAS_DELAY)
        + SUM(SECURITY_DELAY) + SUM(LATE_AIRCRAFT_DELAY), 0), 2) AS LATE_AIRCRAFT_DELAY_PCT
FROM DFW_FLIGHTS.CLEAN.FLIGHT_CLEAN
WHERE (ORIGIN = 'DFW' OR DEST = 'DFW')
    AND CANCELLED = 0
    AND ARR_DEL15 = 1
    AND (CARRIER_DELAY IS NOT NULL OR WEATHER_DELAY IS NOT NULL
        OR NAS_DELAY IS NOT NULL OR SECURITY_DELAY IS NOT NULL
        OR LATE_AIRCRAFT_DELAY IS NOT NULL)
GROUP BY REPORTING_AIRLINE
ORDER BY TOTAL_DELAY_MINS DESC;

-- View 3: Monthly volume and performance trends at DFW
CREATE OR REPLACE VIEW V_MONTHLY_TRENDS AS
SELECT
    YEAR,
    MONTH,
    COUNT(*) AS TOTAL_FLIGHTS,
    SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END) AS CANCELLED_FLIGHTS,
    SUM(CASE WHEN DIVERTED = 1 THEN 1 ELSE 0 END) AS DIVERTED_FLIGHTS,
    SUM(CASE WHEN ARR_DEL15 = 1 AND CANCELLED = 0 THEN 1 ELSE 0 END) AS DELAYED_FLIGHTS,
    ROUND(100.0 * SUM(CASE WHEN ARR_DEL15 = 0 AND CANCELLED = 0 THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*) - SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END), 0), 2)
        AS ARR_ONTIME_PCT,
    ROUND(AVG(CASE WHEN CANCELLED = 0 THEN ARR_DELAY END), 2) AS AVG_ARR_DELAY_MINS,
    ROUND(AVG(CASE WHEN CANCELLED = 0 THEN DEP_DELAY END), 2) AS AVG_DEP_DELAY_MINS,
    ROUND(100.0 * SUM(CASE WHEN CANCELLED = 1 THEN 1 ELSE 0 END)
        / COUNT(*), 2) AS CANCELLATION_RATE_PCT
FROM DFW_FLIGHTS.CLEAN.FLIGHT_CLEAN
WHERE ORIGIN = 'DFW' OR DEST = 'DFW'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
